=== martin-schaefer/postfinance-ebill-client/ebill-client/src/main/xsd/ProcessProtocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Swiss Post Solutions AG -->
<!--W3C Schema generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Envelope">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Header">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="From" type="xs:string"/>
              <xs:element name="To" type="xs:string"/>
              <xs:element name="UseCase" type="xs:string"/>
              <xs:element name="SessionID" type="xs:string"/>
              <xs:element name="Version" type="xs:decimal"/>
              <xs:element name="Status" type="xs:short"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Body">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BillerID" type="xs:string"/>
              <xs:element name="DeliveryDate" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="NumberBills" type="xs:int"/>
                    <xs:element name="OK_Signed" type="xs:int">
                      <xs:annotation>
                        <xs:documentation>Anzahl signierter Rechnungen (entspricht Anzahl OK_Rechnungen)</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="OK_Result" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Signed" type="xs:int">
                            <xs:annotation>
                              <xs:documentation>Anzahl signierter Rechnungen (entspricht Anzahl OK_Rechnungen)</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                          <xs:element name="Bill" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="TransactionID" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="NOK_Result">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="NotSigned" type="xs:int">
                            <xs:annotation>
                              <xs:documentation>Anzahl nicht signierter Rechnungen (entspricht Anzahl NOK_Rechnungen)</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                          <xs:element name="Bill" type="BillType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="date" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="RejectedBills" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="NumberBills" type="xs:int"/>
                    <xs:element name="Bill" type="BillType" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Type" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="BillType">
    <xs:annotation>
      <xs:documentation>Rechnungsdaten</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="TransactionID" type="xs:string"/>
      <xs:element name="EBillAccountID" type="xs:string"/>
      <xs:element name="ESRReference" type="xs:string"/>
      <xs:element name="TotalAmount" type="xs:string"/>
      <xs:element name="ReasonCode" type="xs:string" minOccurs="0"/>
      <xs:element name="ReasonText" type="xs:string" minOccurs="0"/>
      <xs:element name="Date" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== martin-schaefer/postfinance-ebill-client/ebill-client/src/test/resources/ProcessProtocol_Example.xml
<?xml version="1.0" encoding="utf-8"?>
<Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" Type="Response" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\benzth\Desktop\ProcessProtocol.xsd">
	<Header>
		<From>IPEC</From>
		<To>Rechnungsempf√§nger</To>
		<UseCase>GetProcessProtocol</UseCase>
		<SessionID>1</SessionID>
		<Version>1.1</Version>
		<Status>0</Status>
	</Header>
	<Body>
		<BillerID>41101000000111111</BillerID>
		<DeliveryDate date="20120522">
			<NumberBills>5</NumberBills>
			<OK_Signed>3</OK_Signed>
			<OK_Result>
				<Signed>3</Signed>
				<Bill>
					<TransactionID>TID03201207060001-20120602</TransactionID>
				</Bill>
				<Bill>
					<TransactionID>TID03201207060002-20120602</TransactionID>
				</Bill>
				<Bill>
					<TransactionID>TID03201207060003-20120602</TransactionID>
				</Bill>
			</OK_Result>
			<NOK_Result>
				<NotSigned>2</NotSigned>
				<Bill>
					<TransactionID>T456654</TransactionID>
					<EBillAccountID>41010643600000007</EBillAccountID>
					<ESRReference>11220423044000010000000004</ESRReference>
					<TotalAmount>105.50</TotalAmount>
					<ReasonCode>03</ReasonCode>
					<ReasonText>EBillAccountID incorrect format (syntax)</ReasonText>
					<Date>2012-06-12</Date>
				</Bill>
				<Bill>
					<TransactionID>T852258</TransactionID>
					<EBillAccountID>41010643600000008</EBillAccountID>
					<ESRReference>11220423044000010000000005</ESRReference>
					<TotalAmount>110.10</TotalAmount>
					<ReasonCode>08</ReasonCode>
					<ReasonText>ESRCustomerNr check failed</ReasonText>
					<Date>2012-06-12</Date>
				</Bill>
			</NOK_Result>
		</DeliveryDate>
		<RejectedBills>
			<NumberBills>1</NumberBills>
			<Bill>
				<TransactionID>T123456</TransactionID>
				<EBillAccountID>41010643600000000</EBillAccountID>
				<ESRReference>11220423044000010000000000</ESRReference>
				<TotalAmount>100.00</TotalAmount>
				<ReasonCode>25</ReasonCode>
				<ReasonText>eBill Rejected by Customer / Payer</ReasonText>
				<Date>2012-06-12</Date>
			</Bill>
		</RejectedBills>
	</Body>
</Envelope>
